

---
driver:
  name: vagrant
provisioner:
  name: chef_solo
  always_update_cookbooks: true
verifier:
  name: inspec

driver_config:
  box: bento/ubuntu-16.04
  customize:
    memory: 1024


platforms:
  - name: consul-0
    driver_config:
      network:
        - ["private_network", {ip: "10.0.3.240"}]
    attributes:
      consul:
        conf:
          datacenter: "gr-office"
          encrypt: "mlhw8wEnpHejll40nQx/4Q=="
          retry_join: '["10.0.3.241","10.0.3.242"]'
          bind_addr: "10.0.3.240"

  - name: consul-1
    driver_config:
      network:
        - ["private_network", {ip: "10.0.3.241"}]
    attributes:
      consul:
        conf:
          datacenter: "gr-office"
          encrypt: "mlhw8wEnpHejll40nQx/4Q=="
          retry_join: '["10.0.3.240","10.0.3.242"]'
          bind_addr: "10.0.3.241"

  - name: consul-2
    driver_config:
      network:
        - ["private_network", {ip: "10.0.3.242"}]
    attributes:
      consul:
        conf:
          datacenter: "gr-office"
          encrypt: "mlhw8wEnpHejll40nQx/4Q=="
          retry_join: '["10.0.3.240","10.0.3.241"]'
          bind_addr: "10.0.3.242"


suites:
  - name: default
    run_list:
      - recipe[consul::default]
    verifier:
      inspec_tests:
        - test/integration
