

---
driver:
  name: vagrant
provisioner:
  name: chef_solo
  always_update_cookbooks: true
verifier:
  name: inspec
platforms:
  - name: ubuntu-18.04
suites:
  - name: default
    run_list:
      - recipe[consul::default]
    verifier:
      inspec_tests:
        - test/integration
    attributes:
          consul:
            conf:
              datacenter: "gr-office"
              encrypt: "mlhw8wEnpHejll40nQx/4Q=="
              retry_join: ""

            mysql:
              password: "securepassword"
