#
# Use bootstrap: "--bootstrap" on initial run, then disable on second run
# to allow voting. bootstrap is only required for initial cluster formation
# and should be avoided anytime after.

---
driver:
  name: vagrant
provisioner:
  name: chef_zero
  always_update_cookbooks: true
verifier:
  name: inspec

driver_config:
  #box: bento/ubuntu-16.04
  #box: bento/fedora-27
  box: bento/centos-7.5
  customize:
    memory: 1024


platforms:

    #
    # Initial leader node
    #
  - name: consul-0
    driver_config:
      network:
        - ["private_network", {ip: "10.0.3.240"}]
    attributes:
      consul:
        conf:
          bind_addr: "10.0.3.240"
          # NOTE: Must be true for first run, on one node.
          bootstrap: true
          #bootstrap: false
    #
    # Initial follower nodes (bootstap is `false`)
    #
  - name: consul-1
    driver_config:
      network:
        - ["private_network", {ip: "10.0.3.241"}]
    attributes:
      consul:
        conf:
          bind_addr: "10.0.3.241"
  - name: consul-2
    driver_config:
      network:
        - ["private_network", {ip: "10.0.3.242"}]
    attributes:
      consul:
        conf:
          bind_addr: "10.0.3.242"

    #
    # Consul agents
    #
  - name: consul-agent-0
    driver_config:
      network:
        - ["private_network", {ip: "10.0.3.250"}]
    attributes:
      consul:
        conf:
          server: false
          bind_addr: "10.0.3.250"



suites:
  - name: default
    run_list:
      - recipe[consul::default]
    verifier:
      inspec_tests:
        - test/integration
    attributes:
      consul:
        conf:
          ui: true
          datacenter: "office"
          encrypt: "mlhw8wEnpHejll40nQx/4Q=="

          # All node ip's that form the cluster
          # These can be hostnames in an environment with DNS resolution
          retry_join: [
            "10.0.3.240",
            "10.0.3.241",
            "10.0.3.242"
          ]
          acl:
            datacenter: "office"
            default_policy: "deny"
            master_token: "master"
            agent_token: ""
            down_policy: "extend-cache"
